-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'user',
  company text,
  phone text,
  address text,
  wallet_balance numeric default 0,
  emd_blocked numeric default 0,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', coalesce(new.raw_user_meta_data->>'role', 'user'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. AUCTIONS TABLE
create table public.auctions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  base_price numeric not null,
  current_bid numeric default 0,
  location text,
  image_url text,
  quantity text,
  status text default 'active', -- 'active', 'ended'
  seller_id uuid references public.profiles(id),
  ends_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for auctions
alter table public.auctions enable row level security;

-- Policies for auctions
create policy "Auctions are viewable by everyone."
  on public.auctions for select
  using ( true );

create policy "Authenticated users can create auctions."
  on public.auctions for insert
  with check ( auth.role() = 'authenticated' );

create policy "Sellers can update their own auctions."
  on public.auctions for update
  using ( auth.uid() = seller_id );

create policy "Sellers can delete their own auctions."
  on public.auctions for delete
  using ( auth.uid() = seller_id );


-- 3. BIDS TABLE
create table public.bids (
  id bigint generated by default as identity primary key,
  auction_id bigint references public.auctions(id) on delete cascade not null,
  bidder_id uuid references public.profiles(id) not null,
  amount numeric not null,
  status text default 'Leading', -- 'Leading', 'Outbid', 'Won'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for bids
alter table public.bids enable row level security;

-- Policies for bids
create policy "Bids are viewable by everyone."
  on public.bids for select
  using ( true );

create policy "Authenticated users can place bids."
  on public.bids for insert
  with check ( auth.role() = 'authenticated' );


-- 4. TRANSACTIONS TABLE
create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  type text not null, -- 'Credit', 'Debit'
  amount numeric not null,
  description text,
  status text default 'Pending', -- 'Pending', 'Success', 'Failed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for transactions
alter table public.transactions enable row level security;

-- Policies for transactions
create policy "Users can view own transactions."
  on public.transactions for select
  using ( auth.uid() = user_id );

create policy "Users can create transactions (e.g. top-up)."
  on public.transactions for insert
  with check ( auth.uid() = user_id );


-- 5. NOTIFICATIONS TABLE
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  type text not null, -- 'success', 'warning', 'info'
  title text not null,
  message text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for notifications
alter table public.notifications enable row level security;

-- Policies for notifications
create policy "Users can view own notifications."
  on public.notifications for select
  using ( auth.uid() = user_id );

create policy "Users can update own notifications (mark as read)."
  on public.notifications for update
  using ( auth.uid() = user_id );


-- 6. MARKETPLACE ITEMS TABLE (For Material Exchange)
create table public.marketplace_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  price numeric not null,
  quantity text,
  location text,
  image_url text,
  seller_id uuid references public.profiles(id),
  status text default 'active', -- 'active', 'sold'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.marketplace_items enable row level security;

-- Policies
create policy "Marketplace items are viewable by everyone."
  on public.marketplace_items for select
  using ( true );

create policy "Authenticated users can create items."
  on public.marketplace_items for insert
  with check ( auth.role() = 'authenticated' );

create policy "Sellers can update their own items."
  on public.marketplace_items for update
  using ( auth.uid() = seller_id );
  
create policy "Sellers can delete their own items."
  on public.marketplace_items for delete
  using ( auth.uid() = seller_id );
