import React from 'react';
import Logo from '../Logo';
import { BadgeCheck } from 'lucide-react';

interface SustainabilityCertificateProps {
    certificateId: string;
    schoolName: string; // Issued To
    recyclerName: string; // Issued By
    date: string;
    weight: string;
    category: string;
    platformName?: string;
}

const SustainabilityCertificate: React.FC<SustainabilityCertificateProps> = ({
    certificateId,
    schoolName,
    recyclerName,
    date,
    weight,
    category,
    platformName = "EcoBid"
}) => {
    return (
        <div className="bg-white p-8 max-w-[800px] mx-auto text-center border-[10px] border-double border-eco-green/30 relative print:border-[5px] print:w-[100%] print:h-[100vh]">
            {/* Watermark */}
            <div className="absolute inset-0 flex items-center justify-center opacity-[0.03] pointer-events-none select-none">
                <BadgeCheck size={400} />
            </div>

            <div className="relative z-10 space-y-8 py-8">
                {/* Header */}
                <div className="space-y-2">
                    <div className="flex justify-center mb-4">
                        <Logo />
                    </div>
                    <h1 className="text-4xl md:text-5xl font-serif font-bold text-gray-900 uppercase tracking-widest text-eco-green-dark">
                        Certificate of Recycling
                    </h1>
                    <p className="text-sm font-mono text-gray-500">Certificate ID: {certificateId}</p>
                </div>

                {/* Body */}
                <div className="space-y-6 px-8 md:px-16">
                    <p className="text-lg text-gray-600 italic">This certificate is proudly presented to</p>

                    <h2 className="text-3xl font-serif font-bold text-gray-900 border-b-2 border-gray-300 pb-2 inline-block min-w-[300px]">
                        {schoolName}
                    </h2>

                    <p className="text-xl text-gray-700 leading-relaxed font-serif mt-6">
                        "This is to certify that <span className="font-bold">{weight}</span> of <span className="font-bold">{category} Waste</span> collected from {schoolName} on {date} has been processed and recycled in an environmentally sound manner in accordance with the Solid Waste Management Rules, 2016."
                    </p>
                </div>

                {/* Signatures */}
                <div className="grid grid-cols-2 gap-12 mt-16 px-8">
                    <div className="space-y-2 text-center">
                        <div className="h-16 flex items-end justify-center">
                            {/* Digital Signature Placeholder */}
                            <span className="font-cursive text-2xl text-blue-600 transform -rotate-6 block">EcoBid Admin</span>
                        </div>
                        <div className="border-t border-gray-400 w-full"></div>
                        <p className="font-bold text-gray-900">Authorized Signatory</p>
                        <p className="text-xs text-gray-500">{platformName}</p>
                    </div>

                    <div className="space-y-2 text-center">
                        <div className="h-16 flex items-end justify-center">
                            {/* Digital Signature Placeholder */}
                            <span className="font-cursive text-2xl text-gray-600 block">{recyclerName}</span>
                        </div>
                        <div className="border-t border-gray-400 w-full"></div>
                        <p className="font-bold text-gray-900">Authorized Recycler</p>
                        <p className="text-xs text-gray-500">Lic. No: PCB/2024/RW-8291</p>
                    </div>
                </div>

                {/* Footer */}
                <div className="mt-12 text-xs text-center text-gray-400 font-mono">
                    <p>This document ensures zero-landfill policy compliance under ISO 14001 Guidelines.</p>
                    <p>Generated by {platformName} Platform on {new Date().toLocaleDateString()}</p>
                </div>
            </div>
        </div>
    );
};

export default SustainabilityCertificate;
